ansible_network_os: cisco.ios.ios
ansible_user: "{{ lookup('env', 'IOS_USERNAME') }}"
ansible_password: "{{ lookup('env', 'IOS_PASSWORD') }}"
ansible_connection: ansible.netcommon.network_cli

ntp_servers:
  servers:
    - address: 66.85.78.80
      vrf: Mgmt-vrf
    - address: 198.211.103.209
      vrf: Mgmt-vrf
  vrf: Mgmt-vrf

dns_servers:
  servers:
    - server: 10.25.0.52
      vrf: Mgmt-vrf
    - server: 10.25.0.51
      vrf: Mgmt-vrf
  source_interface: GigabitEthernet16
  vrf: Mgmt-vrf
