ansible_network_os: cisco.nxos.nxos
ansible_user: "{{ lookup('env', 'NXOS_USERNAME') }}"
ansible_password: "{{ lookup('env', 'NXOS_PASSWORD') }}"
ansible_connection: ansible.netcommon.network_cli
# ansible_connection: ansible.netcommon.httpapi
ansible_httpapi_use_ssl: true
ansible_httpapi_port: 443
ansible_httpapi_validate_certs: false

global_ospfv2:
  process_id: UNDERLAY
  area_id: 0.0.0.0

ntp_servers:
  servers:
    - address: 66.85.78.80
      vrf: management
    - address: 198.211.103.209
      vrf: management

dns_servers:
  - server: 10.25.0.52
    vrf: management
  - server: 10.25.0.51
    vrf: management

evpn: true
