#cloud-config
# vim: syntax=yaml
# setup hostname, ssk keys, and networking with nopasswd sudo
hostname: dc1-srv1
ssh_authorized_keys:
  - ssh-r dlkfjalk
  - ssh-r dlkfjalk
write_files:
  - path: /etc/sudoers.d/90-cloud-init-users
    content: |
      %sudo ALL=(ALL) NOPASSWD:ALL
    permissions: '0440'
  - path: /etc/hostname
    content: dc1-srv1
  - path: /etc/hosts
    content: |
# configure static networking
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses: [172.16.100.101/24]
      routes:
        - to: 0.0.0.0/0
          via: 172.16.100.1
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
        search: [example.com]
