- name: Configure Nexus global parameters
  hosts: dc2_nexus
  # hosts: dc2-spine1
  gather_facts: false

  roles:
    - nexus_global

  tasks:
    - name: Save configs
      cisco.nxos.nxos_config:
        save_when: modified
        backup: false
