- name: Configure the DC1 spine switches
  hosts: dc1_spines
  gather_facts: false

  roles:
    - nexus

  tasks:
    - name: Save configuration
      cisco.nxos.nxos_config:
        save_when: modified
