---
- name: Configure dc1_wan_routers
  hosts: dc1_wan_routers
  gather_facts: false

  roles:
    - iosxe

  tasks:
    - name: Save configiration
      cisco.ios.ios_config:
        save_when: modified

    # - name: Print output
    #   ansible.builtin.debug:
    #     msg:
    #       - '{{ vrf_config }}'
    #       - '{{ interfaces }}'
    #       - '{{ bgp_config }}'
    #       - '{{ bgp_address_family }}'
