---
- name: Test
  hosts: dc1-leaf1
  gather_facts: false

  roles:
    - nexus

  tasks:
    - name: Print hostvars of dc1-leaf1
      ansible.builtin.debug:
        var: hostvars["dc1-leaf1"]["router_id"]
